<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.9.0.2 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php,v 1.36.2.3.2.1 2006/10/03 13:11:08 nijel Exp $
 * Date: Sat, 14 Oct 2006 11:46:47 GMT
 */

/* Servers configuration */
$i = 0;

/* Server serveur local (config:root) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['controluser'] = 'dicoland';
$cfg['Servers'][$i]['controlpass'] = 'a7sbu14e';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'dicoland';
$cfg['Servers'][$i]['password'] = 'a7sbu14e';
$cfg['Servers'][$i]['verbose'] = 'serveur local';

/* End of servers configuration */

$cfg['ForceSSL'] = false;
$cfg['ShowPhpInfo'] = true;
$cfg['ShowChgPassword'] = true;
$cfg['AllowArbitraryServer'] = false;
$cfg['LoginCookieRecall'] = 'something';
$cfg['LoginCookieValidity'] = 1800;
$cfg['blowfish_secret'] = '56456g456df4g56f4g65fd4g65fdgd';
$cfg['AllowAnywhereRecoding'] = false;
$cfg['DefaultCharset'] = 'iso-8859-1';
$cfg['RecodingEngine'] = 'auto';
$cfg['IconvExtraParams'] = '//TRANSLIT';
?>
